### ISSUE TITLE
Renderer stuck

### ISSUE THREAD

**Issue by wolfand11** [coldnew/hexo-renderer-org#10]
when i run command as below, it's stuck at starting renderer point
```
hexo g
```
the log info is below.
```
guodong on Guos-MacBook-Pro.local in ~/Documents/MyProject/Public/wolfand11(1d7h37m|master)
$ hexo g
add_tail.js
INFO  Start processing

(progn
  ;; file to store debugging information (format: json)
  (setq *debug-file* "/var/folders/ts/904hkwhn0p75mzzschfb5_tm0000gn/T/tmp-29684IsKaH693LxWt.tmp")
  ;; load init.el
  (load "/Volumes/ResourceHD/guodong/Documents/MyProject/Public/wolfand11/node_modules/hexo-renderer-org/emacs/init.el")
  ;; render file according to args
  (hexo-render-org '(:file         "/Volumes/ResourceHD/guodong/Documents/MyProject/Public/wolfand11/source/_posts/HelloWorld.org"
                     :cache-dir    "./hexo-org-cache/"
                     :output-file  "/var/folders/ts/904hkwhn0p75mzzschfb5_tm0000gn/T/tmp-29684bTJJFLoeyxEu.tmp"
                     :htmlize      "true"
                     :theme        "tango-dark"
                     :user-config  ""
                     :common       "#+OPTIONS: toc:nil\n"
                     )))

/Volumes/ResourceHD/guodong/Documents/MyProject/Public/wolfand11/source/_posts/HelloWorld.org start renderer
```

**Comment by coldnew** [comment]
@wolfand11 could you give me your example file?

Also make sure you use the latest version of hexo-renderer-org, which has timer to detect emacs's *Backtrace* buffer error: https://github.com/coldnew/hexo-renderer-org/blob/coldnew/emacs/init.el#L58

**Comment by wolfand11** [comment]
the HelloWorld.org is from your hexo-org-example. And i have check the init.el on my PC, the "run-with-idle-timer" function is exist.

i'll try to add log for the renderer step.

**Comment by coldnew** [comment]
The easiest way for debugging is modify the `lib/renderer.js` following content
```js
var proc = pty.spawn(emacs_path, exec_args, {
      name: 'xterm-256color',
      cols: 100,
      rows: 30
    });

```

to

```js
var spawn = require('child_process').spawn;
var proc = spawn(emacs_path, exec_args, {
   stdio: 'inherit'
});
```

However, this method **ONLY** work on single page, that is you `source/_posts` dir should **ONLY** contain **ONE** org-mode file.

I had test this under Linux/Mac, so I'm not really sure why your hexo stucks there...

**Comment by wolfand11** [comment]
i add log after the pty.spawn, and the log message is "emacs_path=emacs".

the hexo-org-example _config.yml org.emacs is commented。
https://github.com/coldnew/hexo-org-example/blob/master/_config.yml#L79

**Comment by coldnew** [comment]
@wolfand11 mmm, I got it.

In my MacOSX & Linux, I always have command named `emacs` which can help me find emacs on system path. In your example, the `emacs` command didn't exist I think.

I'll add this to the todo-list, if your system already has `emacs` command, it's no need to add `comfig.org.emacs`.

**Comment by wolfand11** [comment]
@coldnew oh, but i can invoke emacs in my terminal. and i run command msg as bellow.
```
$ where emacs
/usr/bin/emacs
```

**Comment by coldnew** [comment]
@wolfand11 
The `/usr/bin/emacs` you use may shipped by MacOSX, which is **emacs-22**.

emacs 22 only has org-mode `4.67c`, maybe that's the problem.

**Comment by wolfand11** [comment]
oh  that's true! it's too late, goodnight.
