### ISSUE TITLE
Package ‘org-plus-contrib-’ is unavailable

### ISSUE THREAD

**Issue by jack2gs** [coldnew/hexo-renderer-org#21]
Hi there,

It reports the error:

> Error: server did not start correctly
> Debugger entered--Lisp error: (error "Package ‘org-plus-contrib-’ is unavailable")
>   signal(error ("Package ‘org-plus-contrib-’ is unavailable"))
>   error("Package `%s-%s' is unavailable" org-plus-contrib "")
>   package-compute-transaction(nil ((org-plus-contrib)))
>   package-install(org-plus-contrib)
>   (progn (setq user-emacs-directory (concat (file-name-as-directory hexo-renderer-org-cachedir) "emacs.d")) (require (quote package)) (if (member (quote ("melpa-stable" . "https://elpa.emacs-china.org/melpa-stable/")) package-archives) package-archives (setq package-archives (append package-archives (list (quote ("melpa-stable" . "https://elpa.emacs-china.org/melpa-stable/")))))) (if (member (quote ("org" . "http://orgmode.org/elpa/")) package-archives) package-archives (setq package-archives (append package-archives (list (quote ("org" . "http://orgmode.org/elpa/")))))) (if (< emacs-major-version 24) (progn (if (member (quote ("gnu" . "https://elpa.gnu.org/packages/")) package-archives) package-archives (setq package-archives (cons (quote ("gnu" . "https://elpa.gnu.org/packages/")) package-archives))))) (package-initialize) (if (not package-archive-contents) (progn (package-refresh-contents))) (package-install (quote org-plus-contrib)) (if hexo-renderer-org--use-htmlize (progn (progn (package-install (quote htmlize)) (require (quote htmlize))))))
>   (if hexo-renderer-org-daemonize (progn (setq user-emacs-directory (concat (file-name-as-directory hexo-renderer-org-cachedir) "emacs.d")) (require (quote package)) (if (member (quote ("melpa-stable" . "https://elpa.emacs-china.org/melpa-stable/")) package-archives) package-archives (setq package-archives (append package-archives (list (quote ("melpa-stable" . "https://elpa.emacs-china.org/melpa-stable/")))))) (if (member (quote ("org" . "http://orgmode.org/elpa/")) package-archives) package-archives (setq package-archives (append package-archives (list (quote ("org" . "http://orgmode.org/elpa/")))))) (if (< emacs-major-version 24) (progn (if (member (quote ("gnu" . "https://elpa.gnu.org/packages/")) package-archives) package-archives (setq package-archives (cons (quote ...) package-archives))))) (package-initialize) (if (not package-archive-contents) (progn (package-refresh-contents))) (package-install (quote org-plus-contrib)) (if hexo-renderer-org--use-htmlize (progn (progn (package-install (quote htmlize)) (require (quote htmlize)))))))
>   eval-buffer(#<buffer  *load*> nil "/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el" nil t)  ; Reading at buffer position 5177
>   load-with-code-conversion("/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el" "/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el" nil nil)
>   load("/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el")
>   (progn (setq hexo-renderer-org-cachedir "./hexo-org-cache/") (setq hexo-renderer-org-user-config "") (setq hexo-renderer-org-theme "") (setq hexo-renderer-org-common-block "#+OPTIONS: html-postamble:nil\n") (setq hexo-renderer-org--debug-file "/var/folders/x_/xgxxwlsn0pz0t3021csdttvm0000gn/T/tmp-29085zj4d0ojCm3iB.tmp") (setq hexo-renderer-org--use-htmlize nil) (setq org-hexo-use-htmlize nil) (setq org-hexo-use-line-number nil) (load "/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el"))
>   eval((progn (setq hexo-renderer-org-cachedir "./hexo-org-cache/") (setq hexo-renderer-org-user-config "") (setq hexo-renderer-org-theme "") (setq hexo-renderer-org-common-block "#+OPTIONS: html-postamble:nil\n") (setq hexo-renderer-org--debug-file "/var/folders/x_/xgxxwlsn0pz0t3021csdttvm0000gn/T/tmp-29085zj4d0ojCm3iB.tmp") (setq hexo-renderer-org--use-htmlize nil) (setq org-hexo-use-htmlize nil) (setq org-hexo-use-line-number nil) (load "/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el")))
>   command-line-1(("--eval" "(progn  (setq hexo-renderer-org-cachedir     \"./hexo-org-cache/\")  (setq hexo-renderer-org-user-config  \"\")  (setq hexo-renderer-org-theme        \"\")  (setq hexo-renderer-org-common-block \"#+OPTIONS: html-postamble:nil\\n\")  (setq hexo-renderer-org--debug-file  \"/var/folders/x_/xgxxwlsn0pz0t3021csdttvm0000gn/T/tmp-29085zj4d0ojCm3iB.tmp\")  (setq hexo-renderer-org--use-htmlize  nil)  (setq org-hexo-use-htmlize            nil)  (setq org-hexo-use-line-number        nil)  (load \"/Users/song/WorkStation/blog/jack2gs.github.io/node_modules/hexo-renderer-org/emacs/hexo-renderer-org.el\"))"))
>   command-line()
>   normal-top-level()
> 
> FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
> INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

**Environment**: macOS X 10.12.5 & GNU Emacs 25.2.1

Thanks,
Jack

**Comment by saccohuo** [comment]
Refreshing the package archive by `M-x package-refresh-contents`, then try it again.

**Comment by jack2gs** [comment]
Hi @saccohuo ,

Have tried that but nothing changed. Any idea? BTW, I use Emacs For Mac OS X app. 

Thanks,
Jack

**Comment by jack2gs** [comment]
Hi all,

I solved it by copying files to ~/.emacs.d to hexo-org-cache/.emacs.d. Now it is solved. But I still didn't know the exact reason.

Thanks,
Jack

**Comment by coldnew** [comment]
@jack2gs The first time execute hexo-renderer-org, it will update package-list and save it to the `hexo-org-cache/.emacs.d`, and will not update the melpa/elpa package-list anymore.

(**NOTE: hexo-renderer-org doesn't share .emacs.d with `~/.emacs.d`, it has it's own .emacs.d in `hexo-org-cache/.emacs.d`**)

In this case, maybe the org-plus-contrib mirror have some problem or else so we can't fetch the manifest in time. To solve this situation, the easiest way is remove the `hexo-org-cache/.emacs.d` and let the emacs regenerate the package-list, or copy needed packages from user's ~/.emacs.d.

**Comment by jack2gs** [comment]
@coldnew I followed the second option. And it does work. Thanks.
