### ISSUE TITLE
some case not support?

### ISSUE THREAD

**Issue by wolfand11** [coldnew/hexo-renderer-org#22]
when i input text as below, blog export will error.

// ## next text will cause error
// #+BEGIN_EXAMPLE
// #+Tile: dired-mode document
// #+BEGIN_HTML
// ---
// layout: page
// title: TEST
// category : tool
// tags : [tool, emacs]
// ---
// {% include JB/setup %}
// #+END_HTML
// #+END_EXAMPLE
# error message:

ERROR Process failed: _posts/tools/CreateBlogWithJeykll.org
YAMLException: name of an alias node must contain at least one character at line 8, column 2:
    \* Jeykll配置
     ^
    at generateError

**Comment by CodeFalling** [comment]
不知道这里的注释符号是要还是不要的，但是无论要不要我这里似乎都没出现这个问题。

**Comment by CodeFalling** [comment]
不知道这里的 // 是要还是不要，但是无论要不要我都没能重现这个问题

**Comment by coldnew** [comment]
這問題是由於 hexo 的 YAML parser 會去抓有 "---" 開頭的東西，當作 YAML 來解析。

(For english user, please see https://github.com/coldnew/hexo-renderer-org/issues/9)

臨時解:在 "---" 開頭行加入 `U200B` 字元，以下是我在 emacs 下加入這字元的命令

```elisp
(defun insert-U200B-char ()
  "Insert <U200B> char, this character is nice use in org-mode."
  (interactive)
  (insert "\ufeff"))
```

由於這問題是在 renderer 之前出現，因此必須自己解決，hexo-renderer-org 無法處理這一塊。

**Comment by coldnew** [comment]
This case can't fix under hexo-renderer-org, close.
For more info, please see above descriptions.
