### ISSUE TITLE
settings in "common" field can not work

### ISSUE THREAD

**Issue by saccohuo** [coldnew/hexo-renderer-org#6]
I set the `org` field as below, but the `#+OPTIONS: num:nil` in `common` field did not work. There are number in headlines on my blog. However, `toc:nil` looks working well.
```
# hexo-renderer-org
## Docs: https://github.com/coldnew/hexo-render-org
org:
  emacs: C:/emacs/bin/emacs.exe
  # emacs: /cygdrive/c/emacs/bin/emacs.exe
  common: |
          #+OPTIONS: toc:nil num:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: ./hexo-org-cache/
  theme: tango-dark
  debug: true
```

**Comment by coldnew** [comment]
Yes, I think I remove these code, I'll add it back.

**Comment by saccohuo** [comment]
Did you try the new version?
I tried it, but there are more problems.
The number in article is still there, and it seems something wrong in the number of content.

**Comment by coldnew** [comment]
Yes I tried it :( 

Maybe I'll try it again later.

**Comment by coldnew** [comment]
Also, make sure the cache is deleted before you test the renderer, or just add some simple modify on your post and save to  trigger hexo-renderer-org to re-render the post.

The render speed is not very good now, but I think I have a nice solution describe in #8 . The patch will be applied after all test is done sine it's a breaking change.

**Comment by saccohuo** [comment]
@coldnew Yeah, it works.
After `hexo clean` and deleted the `hexo-org-cache/`, pages are rendered correctly.
