### ISSUE TITLE
daemon: child name too long

### ISSUE THREAD

**Issue by jasonzhouu** [coldnew/hexo-renderer-org#69]
按照 [Getting Started with the Hexo and org-mode](https://coldnew.github.io/hexo-org-example/2017/03/05/getting-started-with-hexo-and-org-mode/) 教程进行了以下两个操作：
- 安装 hexo-renderer-org
- 更改 _config.yml

然后运行 `hexo generate` 时出现错误：
```
INFO  Start processing
daemon: child name too long
Error: server did not start correctly
```

**Comment by angry-bird** [comment]
同样的问题，自从电脑重装换了emacs26.1后，就没法用了。

**Comment by blindFS** [comment]
+1

**Comment by zhenghub** [comment]
我也遇到这个问题了。在我的fork里解决了这个问题，已经提了PR。如果没有merge，可以先用我的fork里的。
I also met this issue. Fixed this in my fork, and reported a PR. If someone meet this issue again and this pr is not merged, he or she could use my fork.

例如：
For example:

cd /path/to/blog && npm install https://github.com/zhenghub/hexo-renderer-org#emacs --save

**Comment by jiacai2050** [comment]
这个项目已经没人维护了嘛？ @coldnew 这里的 PR 还能合并吗？

**Comment by coldnew** [comment]
@jiacai2050 看了一下，先合併 #73  其他的 PR 還要等我有時間研究一下

這個項目我一直有在用，只是現在很忙維護時間會比較少

**Comment by jiacai2050** [comment]
@coldnew 感谢。
试了下，又遇到新问题了，https://github.com/coldnew/hexo-renderer-org/issues/74
感觉要转 hugo 了，hugo 原生就支持 org。

**Comment by jiacai2050** [comment]
已经转 Hugo 了，完美支持 org-mode
- https://liujiacai.net/blog/2020/12/05/hexo-to-hugo/
