### ISSUE TITLE
load hexo-renderer-org failed

### ISSUE THREAD

**Issue by wolfand11** [coldnew/hexo-renderer-org#7]
when i run below command, i got these error message.
```sh
$ hexo d
```
add_tail.js
ERROR Plugin load failed: hexo-renderer-org
Error: Cannot find module '..\build\Release\pty.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty\lib\windows        PtyAgent.js:4:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty\lib\windows        Terminal.js:8:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty\lib\index.j        s:5:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by coldnew** [comment]
maybe you need to reinstall again, it shows as following:

```
 Error: Cannot find module '..\build\Release\pty.node'
```

hexo-renderer-org need `node-pty` module to make emacs work.

**Comment by wolfand11** [comment]
reinstall hexo-renderer-org or hexo?

**Comment by coldnew** [comment]
@wolfand11 reinstall hexo-renderer-org.

**Comment by coldnew** [comment]
or you can delete the `node_modules` then reinstall by

```
npm install
```

**Comment by wolfand11** [comment]
ths for your reply. install message as below. there are some gyp Error?
```sh
$ npm install
```
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp Do                                                                                                                                                                                                                         S issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> dtrace-provider@0.8.1 install D:\Documents\MyProject\Public\wolfand11\node_modules\dtrace-provider
> node scripts/install.js


> node-pty@0.6.2 install D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty
> node scripts/install.js


D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty>if not defined npm_config_node_gyp (no                                                                                                                                                                                                                         de "D:\Applications\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-g                                                                                                                                                                                                                         yp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "D:\Applications\python\python.EXE" is v3.6.0, which is not                                                                                                                                                                                                                          supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Applications\nodejs\node_modules\npm\node_modules\node-g                                                                                                                                                                                                                         yp\lib\configure.js:454:14)
gyp ERR! stack     at D:\Applications\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js                                                                                                                                                                                                                         :443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\Applications\\nodejs\\node.exe" "D:\\Applications\\nodejs\\node_modules\\npm\\                                                                                                                                                                                                                         node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> node-pty@0.6.2 postinstall D:\Documents\MyProject\Public\wolfand11\node_modules\node-pty
> node scripts/post-install.js


> hexo-util@0.6.0 postinstall D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-util
> npm run build:highlight


> hexo-util@0.6.0 build:highlight D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

hexo-site@0.0.0 D:\Documents\MyProject\Public\wolfand11
+-- hexo@3.2.2
| +-- abbrev@1.1.0
| +-- archy@1.0.0
| +-- bluebird@3.5.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0

**Comment by coldnew** [comment]
Here's the error:

```
gyp ERR! stack Error: Python executable "D:\Applications\python\python.EXE" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

I'm not familiar with Windows, but from #1 , the one use follwoing command can work

```
npm install --python=python2.7 https://github.com/coldnew/hexo-renderer-org#coldnew --save
```

**Comment by wolfand11** [comment]
i'm so sorry to bother you. time to say goodnight, it's too late. 
new errors about gyp as bellow.
```sh
$ npm install

> node-pty@0.6.2 install D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\node                             _modules\node-pty
> node scripts/install.js


D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\node_modules\node-pty>if not                              defined npm_config_node_gyp (node "D:\Applications\nvm\v4.0.0\node_modules\npm\bin\node-gyp-bin\\..\                             ..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (D:\Applications\nvm\v4.0.0\node_modules\npm\node_modules\                             node-gyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (D:\Applications\nvm\v4.0.0\node_modules\npm\node_mo                             dules\request\request.js:1008:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\Applications\\nodejs\\node.exe" "D:\\Applications\\nvm\\v4.0.0\\node_modules\\                             npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\node_modules\nod                             e-pty
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> node-pty@0.6.2 postinstall D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\                             node_modules\node-pty
> node scripts/post-install.js
```

**Comment by coldnew** [comment]
From https://github.com/nodejs/node-gyp/issues/778 , then said following command can fix this problem:

```
npm config set msvs_version=2015 --global
```

Maybe you can try it

**Comment by wolfand11** [comment]
ths, cant get 32-bit node.lib. 
```sh
Administrator on win-10 in ~/Documents/MyProject/Public/wolfand11(64d14h32m|master*)
$ npm config set msvs_version=2015 --global
Administrator on win-10 in ~/Documents/MyProject/Public/wolfand11(64d14h32m|master*)
$ npm install

> node-pty@0.6.2 install D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\node_modules\node-pty
> node scripts/install.js


D:\Documents\MyProject\Public\wolfand11\node_modules\hexo-renderer-org\node_modules\node-pty>if not defined npm_config_node_gyp (node "D:\Applications\nvm\v4.0.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (D:\Applications\nvm\v4.0.0\node_modules\npm\node_modules\node-gyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (D:\Applications\nvm\v4.0.0\node_modules\npm\node_modules\request\request.js:1008:10)
```

**Comment by coldnew** [comment]
mmm... I'm not sure how to solve your question, I don't even have Windows :(.

Anyway, if you still have problem, maybe try this plugin later (about 2 ~ 3 week I think), maybe that time the `node-pty` plugin can be remove from deps.

Or, you can use docker to execute hexo.

**Comment by wolfand11** [comment]
all problem is solved.  deploy operation is ok!  thank you very much! 
the issues should be closed.
